# Generated by Django 4.1 on 2022-11-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialclient',
            name='phone_number',
            field=models.CharField(default='0712345678', max_length=250),
            preserve_default=False,
        ),
    ]
